from chem_suite.core.contracts import ActionSpec, ModuleSpec, OptionSpec

SPEC = ModuleSpec(
    "eis",
    "EIS",
    "0.1.0",
    (
        ActionSpec("fit", "Подбор схемы", "chem_suite.modules.eis.actions:fit_file"),
        ActionSpec("reliable", "Circuit reliability", "chem_suite.modules.eis.research:reliability"),
        ActionSpec("statistics", "Parameter diagnostics", "chem_suite.modules.eis.research:statistics"),
        ActionSpec("series", "Series analysis", "chem_suite.modules.eis.workflows:pooled_series"),
        ActionSpec("joint", "Joint SOC fit", "chem_suite.modules.eis.workflows:joint_series"),
        ActionSpec("resolution", "Synthetic resolution map", "chem_suite.modules.eis.workflows:resolution_map"),
        ActionSpec("controller", "Controller C package", "chem_suite.modules.eis.controller:controller_package", False),
        ActionSpec("research", "Research procedures", "chem_suite.modules.eis.laboratory:run_research", False),
        ActionSpec("presets", "User presets", "chem_suite.modules.eis.presets:manage_presets", False),
        ActionSpec("import_reliable", "Import reliable result", "chem_suite.modules.eis.research:import_reliability", False),
        ActionSpec("drt", "DRT", "chem_suite.modules.eis.advanced:analyze_drt"),
        ActionSpec("parameters", "Parameter defaults", "chem_suite.modules.eis.advanced:parameter_defaults", False),
        ActionSpec("spice", "SPICE package", "chem_suite.modules.eis.advanced:spice_package", False),
        ActionSpec("load", "Загрузка спектров", "chem_suite.modules.eis.actions:load_files", False),
    ),
    "eis",
    options=(
        OptionSpec(
            "circuit",
            "Схема",
            "choice",
            "adaptive",
            ("adaptive", "R0-p(R1,CPE0)", "R0-p(R1,CPE0)-p(R2,CPE1)", "R0-p(R1,CPE0)-Wo0"),
        ),
        OptionSpec("channel", "Канал импеданса (пусто — автоматически)"),
        OptionSpec("restarts", "Начальные приближения", "integer", 1),
        OptionSpec("max_evaluations", "Optimization evaluations", "integer", 5000, minimum=10, maximum=1_000_000),
        OptionSpec("seed", "Random seed", "integer", 0, minimum=0, maximum=2_147_483_647),
        OptionSpec("drt_lambda_grid", "DRT regularization grid", "text", "0.0001,0.001,0.01,0.1,1"),
        OptionSpec("drt_tau_points", "DRT time constants", "integer", 81, minimum=21, maximum=401),
        OptionSpec("drt_folds", "DRT validation folds", "integer", 5, minimum=2, maximum=10),
        OptionSpec("drt_stability_samples", "DRT stability samples (0 = off)", "integer", 0, minimum=0, maximum=200),
        OptionSpec("candidate_circuits", "Candidate circuits (semicolon separated)"),
        OptionSpec("reliability_restarts", "Reliability multistart count", "integer", 3, minimum=1, maximum=100),
        OptionSpec("reliability_samples", "Circuit selection resamples", "integer", 30, minimum=1, maximum=1000),
        OptionSpec("reliability_drt_samples", "Reliability DRT resamples", "integer", 30, minimum=1, maximum=200),
        OptionSpec("statistics_method", "Parameter bootstrap method", "choice", "residual", ("residual", "parametric")),
        OptionSpec("statistics_samples", "Parameter bootstrap resamples", "integer", 100, minimum=1, maximum=1000),
        OptionSpec("statistics_noise_fraction", "Relative noise fraction", "number", "0.01"),
        OptionSpec("profile_parameter", "Profile parameter (empty = off)"),
        OptionSpec("profile_points", "Profile grid points", "integer", 41, minimum=5, maximum=201),
        OptionSpec("profile_span_decades", "Profile span, decades", "number", "0.5"),
        OptionSpec("window_check", "Frequency window check", "choice", "on", ("on", "off")),
        OptionSpec("series_manifest", "SOC series manifest (CSV)"),
        OptionSpec("joint_smoothness", "Joint smoothness", "number", "1"),
        OptionSpec("joint_cv_grid", "Smoothness validation grid (empty = off)"),
        OptionSpec("joint_cv_folds", "SOC validation folds", "integer", 3, minimum=1, maximum=98),
        OptionSpec("resolution_min_frequencies", "Minimum frequency grid, Hz", "text", "0.1,0.03,0.01,0.003,0.001"),
        OptionSpec("resolution_noise_fractions", "Noise fraction grid", "text", "0.005,0.01,0.02"),
        OptionSpec("resolution_max_frequency", "Maximum study frequency, Hz", "number", "2000000"),
        OptionSpec("resolution_replicates", "Study replicates per cell", "integer", 10, minimum=1, maximum=1000),
        OptionSpec("resolution_points", "Study spectrum points", "integer", 81, minimum=21, maximum=401),
        OptionSpec("controller_sample_period_s", "Controller sample period, s", "number", "0.000001"),
        OptionSpec("controller_current_full_scale_a", "Controller current full scale, A", "number", "1"),
        OptionSpec("controller_max_frequency_hz", "Controller maximum frequency, Hz (empty = automatic)", "number"),
        OptionSpec("ngspice_executable", "ngspice executable (empty = automatic)"),
    ),
    supports_directory=True,
)
